### ISSUE TITLE
Ref implementation: revisit downloader design

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#147]
The `l1.Downloader` is designed to handle multiple L2 execution engines attached to the rollup-node at the cost of complexity.

#### Why attach multiple engines to the same rollup-node?

The intention for attaching multiple L2 execution engines is to simplify infrastructure: a larger user like infura may have existing infrastructure to host many execution engines (geth/erigon/other nodes), but not the flexibility to add an extra rollup-node process to each of these instances.

Additionally, in eth2 post-merge a similar infra design problem exists as in our case, but it is much more prohibitive to run a consensus-layer node per execution-engine (beacon-nodes are not stateless, much more heavy than rollup-nodes), thus they are looking at attaching multiple execution-engines to the same beacon-node.

If we assume infura/quicknode/etc. upgrade their infra with minimal changes, and follow the L1 infra design as much as possible for L2, then we need to simplify keeping multiple execution-engines in-sync.

#### Downloader concerns & current remediation

- DoS: fetching L1 information is heavy work (especially when fetching individual receipts), a rollup-node must not fall over when a lot of download requests are being made
  - Back-pressure: after many requests, halt new requests until they can be processed
  - Bounded parallelism: limit amount of parallel receipt downloads
- Multiple engines might all require the same input data (especially in common case where they are all synced to the same block)
  - De-duplicate in-flight requests
  - Cache results with LRU
- Standard RPC does not support downloading of block with all receipts included
  - Have to make individual receipt requests (there can be a lot)
  - Downloader interface can have additional different implementations in the future: detect if the L1 source is geth, we can try a graph-QL implementation to fetch everything at once.
  - Compatibility with standard RPC is important for usability: every user must be able to deploy a rollup-node attached to existing L1 infra.
- Avoid weakest link: e.g. one slow retrieval should not hold back other engines from syncing.
  - context time-outs and cache eviction stopping open tasks

#### Complexity + current drawbacks

Thanks to @trianglesphere for going through the downloader in depth and discussing these:

- Sharing in-flight and past requests in the same cache
- lock around LRU for addition of new tasks is odd
- Blocks are being downloaded without bound (but with deduplication), before queuing up bounded receipt requests. (with expected usage this will always be limited to number of engines though)
- Retries re-use the worker queue (proto: I like this, maybe not great in some other ways)
- `event.Feed` to distribute results to requests with multiple consumers (because of deduplicated request) is heavy for what it is worth
- Adding/Removing workers would be nice to avoid
- Closing is extra work

I am relatively happy with the current trade-offs, and would say we need to do a user-interview of some kind with infrastructure hosts to determine a better L1 data-retrieval strategy. The current implementation is tested + handling the work but can be simplified and/or improved if we have a better idea of infrastructure requirements.

**Comment by trianglesphere** [comment]
A couple extra thoughts on a concurrent downloader
- We're limiting by concurrent requests, not RPS which causes problems when using HTTP nodes (also may be able to solve this with some configuration change). RPS is probably a nicer metric to rate limit on, but may not be worth the extra effort over WS.
- I explored using the Batch RPC API and it is not currently performant enough to solve the problem of getting all receipts.
- While non-standard, using the parity namespace (which has a RPC handler to get all receipts) or some other modification (including another process sitting on the geth node) are options to handle getting lots of receipts
- I'm in favor of separating the de-duplication layer and the concurrent downloader to make it easier to understand. When limiting total in flight requests, there will still need to be a shared semaphore, but otherwise the each component is mostly disjoint


**Problems with highly concurrent HTTP connections.**
When using a HTTP client and using a large amount of concurrency to fetch receipts, there are a lot of short lived HTTP connections that are created. On my mac, these connections then transition to TIME_WAIT and when enough pile up, I get an out of files error. It appears that this might be able to be solved with http://www.unixguide.net/network/socketfaq/4.5.shtml or another configuration change. Websockets and IPC both worked perfectly, even at high levels of concurrent requests.

**Comment by trianglesphere** [comment]
close in favor #187
