### ISSUE TITLE
Code to push L2-output-roots to L1

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#170]
Modifying the batch submitter for 1.0.

**Comment by protolambda** [comment]
@cfromknecht implemented this: https://github.com/cfromknecht/optimism/commit/d5811893b6f5e499125f7894240cfd4f7a06cfa0

Based on updated L1 contract code here: https://gist.github.com/karlfloersch/02ce7938000680ce7820f39ba06bd9b1?permalink_comment_id=4044915#gistcomment-4044915

We have 2 options for integration:
1. Batch-submitter into separate repo
2. Batch-submitter into specs repo

Option 2 seems better to me, considering:
- The batchsubmitter is larger with more pre-1.0 things, making it somewhat difficult to make a minimal copy: it includes a tx-manager, some crypto to load private key, metrics, mocking, and gas-price utils: https://github.com/cfromknecht/optimism/tree/bss-output-commitment/go/batch-submitter
- The batchsubmitter imports `github.com/ethereum-optimism/optimism/l2geth` for "L2 ethclient" (extra RPC bindings), but also `github.com/ethereum/go-ethereum`. We are not using that RPC or the old L2 types (non-standard transactions), and we are trying to move away from go-ethereum modifications, so I think we need to refactor this out somehow.
- We do not need the old proposer part of the batch submitter
- Some of the sequencer part of the batch-submitter is useful if we adapt it to submit 1.0 transaction batches, but it is built for a single transaction per L2 block (not the case anymore in 1.0), and the older non-standard tx type system.
- Half of the metrics/flags are not really relevant, since they refer to the old contracts/terms/etc.
- If we do try and de-duplicate, we have two different modes of development on the same critical code (continuously changing 1.0 work, and production-critical pre-1.0 work)
- Integration/testing with changing smart-contracts in the 1.0 specs repo would be easier if it moves to the specs repo
