### ISSUE TITLE
Ref Impl: Engine API: Worst case sync

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#72]
Transferred from ENG-1742

**Comment by protolambda** [comment]
Update: #88 implements sync from L1, by scheduling, then downloading, then running the driver for each of the engines. That covers the input-part of worst-case sync. And it includes a first attempt at API calls to get the derived blocks into the engine. But the driver is just a placeholder.

This issue is completed once the driver is done and integrated and we can test/polish those API calls to the engine.
