### ISSUE TITLE
Clarify approach to charging gas fees on deposits

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimistic-specs#78]
Transferred from ENG-1785

**Comment by norswap** [comment]
I consider the clarification complete. Upon further reflection, I don't see any issue with charging for L2 gas on L1, based on the cost of L1 gas divided by a constant (which it should be said, is how things currently work!).

We should discuss whether we want deposit fees to be part of the deposit rollup milestone, or to be tackled later.

**Comment by norswap** [comment]
There is however, an additional concern that needs to be raised: do we implement a gas limit for deposit blocks? I'd be in favour of not doing it — the intrinsic L1 costs + L2 gas fee will make sure we can never end with absurdly sized deposit blocks. Even a whole L1 block filled with deposits will only yield at best a deposit block that is at worst 4x bigger  than a normal Ethereum block, which we should be able to handle easily. (The lever comes from the stipend, assuming the L2 gas stipend is < 4x L1 gas cost of deposit.)

**Comment by ben-chain** [comment]
Sorry that I'm just getting to this after sickness & the holidays; I do have some thoughts.

> We should discuss whether we want deposit fees to be part of the deposit rollup milestone, or to be tackled later.

I definitely don't think we should let this be a blocker for this milestone.  Most importantly, I still think we need a lot more input from our integrations team and and people with experience using the dev-ex, and I don't want that discussion to block deposit rollup work.  This one is high-impact for sure--we need to hear from more people on this.

@norswap , I think your proposal is a solid option, and easier to implement, but I would still like to discuss the "paying on L2" option just a bit more.  After thinking about it, my *guess* is that this depends on how optimal we want deposit gas costs, and how we need to parameterize the EIP1559 impacting deposits, wherever it lives.

>In both cases, the concern is that it becomes possible to submit a deposit on L1 that won't be executable on L2 because of a lack of L2 funds. [**This is not good UX.**] Mitigations include the possibility of "replaying" a previous deposit by adding to the L2 fee. However, given the L1 cost of submitting a transaction dominates, this is still a very unhappy & costly path. And the UX isn't improved compared to just resubmitting the transaction.

Both proposals require deposit replays in some cases, so the UX choice is actually not immediately obvious to me. I can think of two UX questions:
1. What is the UX of submitting the replay in either case?
2. What is the chance of having to replay in either case?

Answering 1., it could arguably be better if transaction replaying was implemented on L2--since replays would be cheaper & instant. It may also make the deposits themselves much cheaper, being just an event vs. an L1 storage write for updating the basefee in the deposit contract.

Answering 2., I think it entirely depends on the EIP1559 implementation. For Deposit Rollup, I would imagine the probabilities are equal for a basic implementation. With the introduction of a sequencing window, I think it's more complex. If the L2 `BASEFEE` moves sufficiently slowly/quickly, I think it could go either way. You can also have "two" basefees for each tx type, but that feels pretty ugly. I think @karlfloersch / @protolambda have discussed a fast EIP1559 for the sequencer, so that could be an issue.

I also think that implementing the replays on L2 is much harder; it's definitely a heavier lift as I see it.  You have to validate the failed deposit and check that it a) really happened and b) wasn't already applied. Would be curious for @protolambda 's take on what implementing this look like. Possibilities:
1. The replay tx can specify an index for the failed deposit, and the engine looks it up in the old block.
2. If a deposit can't pay up on L2, we divert a call frame to some system contract/predeploy, or otherwise record the failure in the state, and give a way to replay that.

Overall, still on the fence, and I still wanna hear from others.

**Comment by protolambda** [comment]
Regarding deposit congestion control:
- There should definitely be a way to guarantee a transaction from L1 without repeating it, even at a higher price. Not having this option affects potential integrations, cc @K-Ho 
- Assuming we want to both minimize fees and enable above always-through, refunding the difference (if any) seems nice to have (i.e. fee is locked on L1, part of the total L2 balance, and refunded to sender on L2)
- Failing deposits is natural for some use-cases like cross-chain arbitrage. Stopping execution if arbitrage turns out to be gone, and get refunded as much gas as possible.

----

@ben-chain 

> Would be curious for @protolambda 's take on what implementing this look like

I don't like the replay-on-fail approach, it introduces per-user state on L2. And we have to either fail all later transactions of the same user, or store every failed tx per user. And a failed deposit of one user shouldn't halt other users from depositing, yet synchronous deposits may be important to guarantee in some cases.

Option 1: Storing the block-height and transaction index of failed deposits sounds reasonable to me. It's like storing all failed txs per user, but is easy to prune history of if size ever becomes a problem. It could look like a single storage write to some predeployed read-only contract. And then you could read if it was a failure (i.e. if it can be replayed) only for deposits that specify themselves as a replay (to avoid overhead on other deposits), and then essentially substitute the data/value/mint fields with the previously failed deposit, and keep the new fee payment.

Maybe there is a better option with a little bit more thought, but I would still prefer an option that at least enables guaranteed processing on L2 for UX reasons. Not introducing too much changes to the L2 state updates would also help keep the diff small.

**Comment by ben-chain** [comment]
In the interest of soliciting external feedback, I'm going to try to write each tradeoff as succinctly as possible for readers. Here's how I would put it:

# Problem Statement
We would like to make deposits as cheap as possible in the happy case.  In 1.0, we can get the L1 gas down to <5k, which would open up a DoS if unchecked.  We need a way to block/increase the cost of deposits if they start getting spammed.  We've identified two main approaches, corresponding to 1 and 2 in the first section [here](https://github.com/ethereum-optimism/optimistic-specs/discussions/32#discussioncomment-1621163).

A) L1 EIP1559 mechanism: the deposit contract on L1 limits deposit frequency by increasing cost under congestion.
B) L2 EIP1559 mechanism: the L2 VM limits deposit frequency by increasing cost under congestion.

# Tradeoffs
Here's what the effects of these options are.

## Failure Mode UX
- In option A), there is a chance for your L1 deposit TX reverting up front.
- In option B) there is a chance for your L1 deposit TX succeeding, but the L2 TX being rejected. We can implement the ability to replay the second half from L2.

Both failure modes require that users replay the deposit TX (from L1 in A, from L2 in B), but option B) is worse. This is because the L1 half of the transaction still succeeds, causing devex issues.

## Cost
- In option A), we must perform an L1 `SSTORE` overwrite to track the deposit frequency.
- In option B), we track it in L2, so no L1 `SSTORE`.

It is [possible to implement option B without any `SSTORE`s at all](https://github.com/ethereum-optimism/optimistic-specs/issues/14), so the cost could more than double for small payloads in option A.

## Failure Mode Likelihood
- In both cases, users can overpay (and get the ETH refunded on L2) to decrease the likelihood of a failure.
- In both cases, the cost of a spam attack to force failures should be pretty similar.  (can someone check me on this? see below, option A may be worse)
- L2 congestion may be more volatile, which would cause failures in B) to be more likely. (In other words, option A requires that *deposits* get congested to trigger the fail, option B could arise from *L2* congestion itself.)

## Difference in Ratelimit Trigger
- In option A), the ratelimit would kick in based on the sum of L2 `gasLimit` values.
- In option B), the ratelimit could kick in based on the sum of L2 `gasUsed` values.

This is minor, but it does mean that option A) will trigger more easily/at lower throughput.  If we refund the extra ETH paid in option A), we will have to deal with an attacker's deposit consuming very little gas on L2, or else the cost of a spam attack would be significantly lower for option A). The mitigation I see is probably to reinforce a minimum gas usage or only refund above a certain amount or % of gas, but it may make the cost of attack proportionally cheaper in A).

**Comment by maurelian** [comment]
Please move response to the previous comment here: https://github.com/ethereum-optimism/optimistic-specs/discussions/112

**Comment by norswap** [comment]
Here's a comment I sent to Ben with the idea of jelling some stuff synchronously. I don't think he has seen it before posting his thing, so I'm posting it here for clarity.

(sorry @maurelian , unlocking this temporarily for clarity since it quotes directly from above, will relock after)

> After thinking about it, my guess is that this depends on how optimal we want deposit gas costs, and how we need to parameterize the EIP1559 impacting deposits, wherever it lives.

Here I probably wasn't clear enough, but the main idea right now is to move away from the proposal where there is a congestion control system (EIP-1559 or other) on L1, and to just keep the current solution of charging users in proportion to the L2 gas (either by burning L1 gas or by having them pay us directly). The rationale: that's the solution that minimizes cost the most, while still avoiding the possibility of a L2 DoS via deposits.

> Both proposals require deposit replays in some cases, so the UX choice is actually not immediately obvious to me. I can think of two UX questions:

That is not how I would put it exactly. The "both proposals" you're referring to here are cases where we pay the fee on L1. They don't require "replay" in the sense that **if the L1 transaction succeeds, then the transaction will land on L2**.

The danger I was alluding to is the risk that the L1 transaction itself reverts, which could happen if the "L2 gas price (as charged on L1)" changes. Note that if we burn L1 gas proportional to L2, then this issue disappears completely. (It might still exist in the case of charging via an ETH transfer - if we base the ETH price on the current L1 gas price. However, the discount might make it feasible to set a higher priority fees to mitigate this issue. In any case, the gas burn route is a safe default.)

**Comment by smartcontracts** [comment]
Some stream-of-consciousness notes on my end:

1. If we're going to charge users on the L1 side, I think a gas burn is still the best UX. Without a gas burn we need to charge users in some token which would almost certainly be ETH (unless there's another way to rate limit on the L1 side that I'm not thinking about). If we have to charge users ETH, then everyone needs to start adding `payable` keywords to every contract that sends messages to L2 which would be a complete devex headache. So if we're going to charge on the L1 side, we should stick with a gas burn.

2. With respect to [the matrix defined here](https://github.com/ethereum-optimism/optimistic-specs/discussions/32#discussioncomment-1621163) by @ben-chain, I would prefer (1, 1) but could possibly be convinced of (2, 1). However, (2, 1) would have to come with a mechanism for *any* account to pay for the gas to replay a transaction. This seems like a major headache for devex and ux, I'd prefer not to have this.

2. If we charge on the L2 side, doesn't that mean users need ETH on L2? I assume this means we need some special deposit logic that allows users to deposit ETH so they can pay for further actions on L2. Could introduce some UX headaches for users who just want to deposit some tokens and don't also want to deposit ETH.

3. I see some potential complexity around smart contracts. Smart contracts can have the same address on both L1 and L2 but might have different code. How do smart contracts (and smart contract wallets in particular) define the address who's going to pay for the deposit cost on L2?

Generally speaking, after thinking about this more, **I feel that we should treat accounts on L1 and L2 as fundamentally different and that we should have the L1 account pay for the action on L1.** In particular, I think this should be done as a gas burn on L1 like we currently do.

I think the main question to be answered then is how we determine the burn ratio, effectively "how much is L2 gas worth right now relative to L1 gas?". I feel that we will ultimately have to come up with an automated mechanism to handle this some time in the future. Any fixed value that we choose will either have to be extremely expensive or will eventually be so cheap that it's more efficient to send all transactions on L1 instead of going through the Sequencer.

Using a dynamic fee means getting information from L2 that tells us how congested L2 is. Congestion can spike up or down in the short term and it takes 7 days for information to flow from L2 to L1. However, it might be the case that this doesn't matter on short time windows and we can get away with using the `BASEFEE` from L2 to constantly update the ratio on L1, even if we're a week behind. Deposit gas costs would increase in response to macro trends but would not be impacted significantly by short-term trends. This is the sort of thing where we would have to do the math on the potential impact that someone spamming deposits could actually have on the network.
